### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by afaerber** [AntonioND/rpi3-arm-tf-bootstrap#1]
Source code files indicate `SPDX-License-Identifier: BSD-3-Clause`, but there is no text file in the repository spelling out that license. In particular it is not mentioned anywhere who the party of the third clause is supposed to be here.

**Comment by AntonioND** [comment]
True, I'll fix this later. I'm thinking about MIT instead, is that ok?

**Comment by afaerber** [comment]
I don't mind either way. Thanks!

**Comment by AntonioND** [comment]
Done in https://github.com/AntonioND/rpi3-arm-tf-bootstrap/commit/17be97405b2580623e3caf9c8f292af4996f080c . If there is anything missing, tell me.

I don't know why I chose BSD-3, it didn't really make sense. There aren't a thousand variations of MIT like with BSD, so it's probably better. I don't even know if it makes sense to license such a simple piece of code...
